#version: '3.9'

services:
  neo4j:
    image: neo4j:5.7
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - ./neo4j_data:/data
    networks:
      - drugvi-network

  api:
    build:
      context: ./api
    #dockerfile: Dockerfile.api
    container_name: drugvi-api
    environment:
      #- FLASK_APP=${FLASK_APP}
      #- FLASK_ENV=${FLASK_ENV}
      #- NEO4J_URI=${NEO4J_URI}
      - FLASK_APP=main.py
      - FLASK_ENV=development
      #- NEO4J_URI=${NEO4J_URI}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./api:/app
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - neo4j
    networks:
      - drugvi-network

  cli:
    build:
      context: ./cli
    #dockerfile: Dockerfile.cli
    container_name: drugvi-cli
    environment:
      #- NEO4J_URI=${NEO4J_URI}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - CLI_DATA_DIR=${CLI_DATA_DIR}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./cli/data:/app/data
    depends_on:
      - neo4j
    networks:
      - drugvi-network
    entrypoint: ["python", "main.py"]

  web:
    build:
      context: ./web
    #dockerfile: Dockerfile.web
    container_name: drugvi-web
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules      
    depends_on:
      - api
    networks:
      - drugvi-network

volumes:
  neo4j_data:

networks:
  drugvi-network:
    driver: bridge